services:
  postgres:
    image: postgres:16.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=!@#123qwe
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data